name: Manual workflow for automated tests windows10

on:
  workflow_dispatch:
    inputs:
      suites:
        description: 'Test suites'
        required: false
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14.17.0
      - name: Setup
        run: npm install
      - name: Test (when added suite flag)
        shell: bash
        env:
          SUITES: ${{ github.event.inputs.suites }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        if: ${{ github.event.inputs.suites != null || '' }}
        run: node prepareConfig.js --envSecretUser "$USER_NAME" --envSecretPwd "$USER_PASSWORD" && ./node_modules/.bin/wdio ./wdio-github.conf.js --suite "$SUITES"
      - name: Test (when no suite flag)
        shell: bash
        env:
          SUITES: ${{ github.event.inputs.suites }}
         USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        if: ${{ github.event.inputs.suites == null || '' }}
        run: node prepareConfig.js --envSecretUser "$USER_NAME" --envSecretPwd "$USER_PASSWORD" && ./node_modules/.bin/wdio ./wdio-github.conf.js
      - name: Screenshot handling
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: wdio-error-screenshots
          path: errorScreenshots